name: Build
on: [push, pull_request]
jobs:
  check:
    name: 'Gradle Wrapper check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
  build:
    name: 'JDK: Temurin ${{ matrix.Java }}'
    runs-on: ubuntu-latest
    needs: check
    strategy:
      matrix:
        java: [ '8', '11', '17' ]
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - run: ./gradlew build
